version: "3.9"

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    command: python main.py  # или gunicorn, если ты используешь FastAPI/Flask

  mongo:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
