name: Publish NeonPay to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install build tools
      run: pip install build

    - name: Build NeonPay package
      run: python -m build

    - name: Publish NeonPay to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__                    
        password: ${{ secrets.PYPI_API_TOKEN }}
